Update pipeline

diff --git a/.github/workflows/terragrunt-deploy.yml b/.github/workflows/terragrunt-deploy.yml
--- a/.github/workflows/terragrunt-deploy.yml
+++ b/.github/workflows/terragrunt-deploy.yml
@@ -1,9 +1,8 @@
 name: Terragrunt Deploy
-
 on:
   repository_dispatch:
-    types: [trigger-deploy]  # Triggered from infra-modules repo
-  workflow_dispatch:  # Manual trigger via GitHub UI
+    types: [trigger-deploy] # Triggered from infra-modules repo
+  workflow_dispatch: # Manual trigger via GitHub UI
 
 permissions:
   id-token: write
@@ -13,41 +12,41 @@ jobs:
   deploy:
     name: Deploy Terragrunt Infra
     runs-on: ubuntu-latest
-
+    env:
+      REPO_DISPATCH_PAT: ${{ secrets.REPO_DISPATCH_PAT }}  # Add this line
     defaults:
       run:
         shell: bash
-        working-directory: Dev  # Adjust this if you're deploying Prod or Staging
-
+        working-directory: Dev # Adjust this if you're deploying Prod or Staging
     steps:
       - name: Checkout Live Infra
         uses: actions/checkout@v4
-
+        
       - name: Configure AWS Credentials with OIDC
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::649203810550:role/EksOIDCRole
           aws-region: eu-west-1
-
+          
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.6.6
-
+          
       - name: Install Terragrunt
         run: |
           curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
           chmod +x terragrunt
           sudo mv terragrunt /usr/local/bin/
-
+          
       - name: Format Check (Terragrunt)
-        run: terragrunt hclfmt --terragrunt-check || true  # not failing pipeline yet
-
+        run: terragrunt hclfmt --terragrunt-check || true # not failing pipeline yet
+        
       - name: Terragrunt Validate
-        run: terragrunt run-all validate
-
+        run: terragrunt validate --all  # Updated command as warned
+        
       - name: Terragrunt Plan
         run: terragrunt run-all plan --terragrunt-non-interactive
-
+        
       - name: Terragrunt Apply
         run: terragrunt run-all apply --terragrunt-non-interactive --terragrunt-include-external-dependencies -auto-approve
